### PR TITLE
add japanese localization

### PR DESCRIPTION
**Pull request by BrotherSharper**
I have taken the liberty to swap the english FVTT's discord link to the Japanese FVTT discord link so we can better support new users. If you would like me to revert this part of the localization I can easily do so.

### CODE REVIEW

**Comment by ruipin** [comment]
Thank you very much for your contribution! From my beginner-level JP knowledge (~N5), this looks great.

As for the Discord links, you are able to easily add new ones. See e.g. the [ES](https://github.com/ruipin/fvtt-lib-wrapper/blob/master/lang/es.json#L120-L134) and [PT](https://github.com/ruipin/fvtt-lib-wrapper/blob/master/lang/pt-BR.json#L120-L134) translations.

As such, I think it might be better to do the same thing as there, and include the English Discord as well. Something like:

````js
"support-channels": [
	{
		"title": "オンセ工房FVTTの日本支部サーバ",
		"url": "https://discord.gg/vM4YM27"
	},
	{
		"title": "FoundryVTT Discord (英語のみ)",
		"url": "https://discord.gg/foundryvtt"
	},
	{
		"title": "FoundryVTT Reddit（英語のみ）",
		"url": "https://www.reddit.com/r/FoundryVTT"
	}
]
````

What do you think?

**Comment by BrotherSharper** [comment]
@ruipin Thank you!
I did indeed not know you could add custom links, I will take up your suggestion and update the pull request immediately!

**Comment by BrotherSharper** [comment]
I sent the update, cheers!

**Comment by ruipin** [comment]
This has been merged, and included into [v1.11.1.0](https://github.com/ruipin/fvtt-lib-wrapper/releases/tag/v1.11.1.0). Thanks!

**Pull request merged**
